version: "3.8"

services:

  mongo_db:
    image: mongo:4.0
    restart: always
    volumes:
      - ./db/mongo/data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - neurotask_overlay
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 1
      restart_policy:
        condition: on-failure




  micro_user:
    image: stevenvega/micro_user:v1
    ports:
      - target: 3009
        published: 3009
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  micro_projects:
    image: stevenvega/micro_projects:v1
    ports:
      - target: 3008
        published: 3008
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  micro_task:
    image: stevenvega/micro_task:v1
    ports:
      - target: 3007
        published: 3007
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  micro_coments:
    image: stevenvega/micro_coments:v1
    ports:
      - target: 3010
        published: 3010
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s


  micro_analisis:
    image: stevenvega/micro_analisis:v7
    ports:
      - target: 3011
        published: 3011
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  sparkanalytics:
    image: stevenvega/sparkanalytics:v3
    networks:
      - neurotask_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



  prometheus:
    image: prom/prometheus
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: ingress
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - neurotask_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - neurotask_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kong:
    image: kong:3.4
    ports:
      - 8000:8000 
      - 8443:8443  
      - 8001:8001   
    volumes:
      - ./kong.yaml:/kong/declarative/kong.yaml:ro
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    restart: always
    networks:
      - neurotask_overlay

networks:
  neurotask_overlay:
    driver: overlay
